[bar]
scale = 1.0

[modules.hyprland-workspaces]
min-workspace-count = 4

[wallpaper]
cycling-enabled = true
cycling-directory = "/home/deuley/Pictures/wallpapers/Misc"
cycling-interval-mins = 18

[[wallpaper.monitors]]
name = ""
fit-mode = "fill"
wallpaper = ""
