#!/usr/bin/env bash
# idle-power.sh — power-aware idle policy for hypridle.
#
# hypridle has no native awareness of the power profile or AC state, so this
# script owns hypridle's lifecycle instead: it generates a hypridle config from
# the (power-profile × AC) matrix below, (re)starts hypridle against it, and
# then watches for power changes and regenerates on the fly.
#
# Started from hyprland.lua autostart (replaces a bare `hypridle` exec). The
# generated config lives in $XDG_RUNTIME_DIR so the static ~/.config/hypr/
# hypridle.conf is no longer consulted.
#
# Screensaver + lock note: hyprsaver is a passive layer-shell overlay and does
# NOT authenticate. A hyprlock session-lock would render *above* it, hiding the
# animation, so we can't show the saver and a lock simultaneously. Instead the
# saver runs while idle and its on-resume does `hyprsaver --quit; hyprlock` —
# any input drops straight into a mandatory password prompt, so the session is
# effectively locked the entire time the saver is up.

POLL_INTERVAL=10
RUNTIME_CONF="${XDG_RUNTIME_DIR:-/tmp}/hypridle.conf"
AC_ONLINE=/sys/class/power_supply/ADP1/online

# key = "<profile>:<ac|bat>"  ->  "<dim> <saver+lock> <screen-off> <suspend>"
# all values in seconds; suspend = 0 means "never suspend".
declare -A MATRIX=(
  ["power-saver:bat"]="150 300 420  900"
  ["power-saver:ac"]="150 300 900  3600"
  ["balanced:bat"]="300 420 600  1200"
  ["balanced:ac"]="300 420 1200 3600"
  ["performance:bat"]="300 420 1200 3600"
  ["performance:ac"]="300 600 3600 0"
)

ac_state() {
  [ "$(cat "$AC_ONLINE" 2>/dev/null || echo 0)" = "1" ] && echo ac || echo bat
}

profile() {
  powerprofilesctl get 2>/dev/null || echo balanced
}

current_key() {
  echo "$(profile):$(ac_state)"
}

gen_conf() {
  local key="$1" vals dim saver off susp
  vals="${MATRIX[$key]:-${MATRIX[balanced:ac]}}"
  read -r dim saver off susp <<<"$vals"

  cat >"$RUNTIME_CONF" <<EOF
# Auto-generated by idle-power.sh — profile/AC = $key. Do not edit by hand;
# adjust the MATRIX in ~/.config/hypr/scripts/idle-power.sh instead.
general {
    lock_cmd = pidof hyprlock || hyprlock                                   # avoid stacking hyprlock instances
    before_sleep_cmd = loginctl lock-session                                # lock before suspend
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' # wake the display on resume
    ignore_dbus_inhibit = false                                             # honor app idle-inhibit (e.g. fullscreen video)
}

# Dim the screen backlight (min, not 0 — OLED).
listener {
    timeout = $dim
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# Turn off the keyboard backlight.
listener {
    timeout = $dim
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

# Screensaver + lock: show the saver while idle; any input quits it and demands
# a password, so the session is effectively locked for the whole idle period.
listener {
    timeout = $saver
    on-timeout = hyprsaver
    on-resume = hyprsaver --quit; pidof hyprlock || hyprlock
}

# Screen off (DPMS).
listener {
    timeout = $off
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}
EOF

  if [ "${susp:-0}" -gt 0 ]; then
    cat >>"$RUNTIME_CONF" <<EOF

# Suspend.
listener {
    timeout = $susp
    on-timeout = systemctl suspend
}
EOF
  fi
}

restart_hypridle() {
  pkill -x hypridle 2>/dev/null || true
  hypridle -c "$RUNTIME_CONF" >/tmp/hypridle.log 2>&1 &
}

LAST=""
apply() {
  local key
  key="$(current_key)"
  [ "$key" = "$LAST" ] && return
  LAST="$key"
  gen_conf "$key"
  restart_hypridle
  notify-send -t 3000 -a hypridle "Idle policy" "profile: ${key/:/ · }" 2>/dev/null || true
}

apply
while true; do
  sleep "$POLL_INTERVAL"
  apply
done
